environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g karma-cli

test_script:
  - .\node_modules\.bin\karma start karma.conf.js --single-run